linters-settings:
   lll:
      line-length: 130
   revive:
      rules:
        - name: var-naming
          arguments: [["ID"]]
   gosec:
      excludes:
        - G404
   wrapcheck:
      ignorePackageGlobs:
        - github.com/dictyBase/aphgrpc
        - github.com/dictyBase/arangomanager
        - github.com/arangodb/go-driver
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - bidichk
    - cyclop 
    - decorder
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errname
    - funlen
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - gocognit
    - gomnd 
    - gomoddirectives
    - gomodguard
    - grouper
    - ineffassign
    - importas
    - lll
    - maintidx
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - nolintlint
    - prealloc
    - paralleltest
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - thelper
    - tparallel
    - unparam
    - unused
    - unconvert
    - unparam
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck

  # don't enable:
  # - godox
  # - maligned,prealloc
  # - gochecknoglobals
  # - golint
  #  - forcetypeassert
