name: Continuous integration
on: 
 push:
   branches:
     - develop
 pull_request:
   branches-ignore:
     - master
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v1
        with:
            go-version: 1.11.13
      - name: check out code
        uses: actions/checkout@v1
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.0.3
        with:
            file: ./profile.cov
            token: ${{ secrets.CODECOV_TOKEN }}
