name: Lint golang code 
on: 
  pull_request:
    branches-ignore:
      - master
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - name: set up golang
        uses: actions/setup-go@v3
        with:
            go-version: 1.18
      - name: run linter
        uses: golangci/golangci-lint-action@v3
