name: Lint golang code 
on: 
  pull_request:
    branches-ignore:
      - master
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up golang
        uses: actions/setup-go@v2
        with:
            go-version: 1.17
      - name: run linter
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "-c .golangci.yml"
          go_version: 1.17
