name: Release
on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    runs-on: latest
    steps:
      - name: set up nodejs
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: install semantic release
        run: npm i -g semantic-release@25
      - name: check out code
        uses: actions/checkout@v6
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
