name: Release 
on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    runs-on: ubuntu-20.04
    steps:
      - name: set up nodejs
        uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: install semantic release
        run: npm i -g semantic-release@~17.4.2
      - name: check out code
        uses: actions/checkout@v3
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
